### ISSUE TITLE
Problem when install

### ISSUE THREAD

**Issue by starofsky** [alcaitiff/laravel-urlencode#1]
Hi,
I installed your package on Laravel 5.8 but I also got not found on any route.
Below function I used:
`use Alcaitiff\LaravelUrlEncode\Routing\Router;`
`public function setRouter(Router $router) {
    $this->router = $router;
    return $this;
  }`

Do you have any suggestion?

**Comment by alcaitiff** [comment]
Did you put this function on your App\Http\Kernel? 

Did you added the provider? 

Your apache has the AllowEncodedSlashes on?

**Comment by alcaitiff** [comment]
Closed by inactivity
